<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>framework7root</name>
   <tag></tag>
   <elementGuidId>5276e010-c33e-488e-be3b-d14c0b7694af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#framework7-root</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
